<?php
use Icinga\Web\Url;

/** @var \Icinga\Web\View $this */
/** @var \Icinga\Module\Monitoring\DataView\DataView $hosts */

if (! $compact): ?>
<div class="controls">
    <?= $tabs ?>
    <?= $paginator ?>
    <div class="sort-controls-container">
        <?= $limiter ?>
        <?= $sortBox ?>
    </div>
    <?= $filterEditor ?>
</div>
<?php endif ?>
<div class="content">
<?php if (! $hosts->hasResult()): ?>
    <p><?= mt('monitoring', 'No hosts found matching the filter.') ?></p>
</div>
<?php return; endif ?>
<?php foreach ($hosts->peekAhead($compact) as $host): ?>
    <h2><?= $this->qlink(
        $host->host_name === $host->host_display_name
            ? $host->host_display_name
            : $host->host_display_name . ' (' . $this->escape($host->host_name) . ')',
        Url::fromPath('monitoring/host/show', ['host' => $host->host_name])
    ) ?></h2>
    <div class="container" data-base-target="_main" data-last-update="-1" data-icinga-refresh="15" data-icinga-url="<?=
        // TODO(ak): EL says "<div class="container" data-icinga-url="..." /> is enough", but this seems not to work for me
        $this->href('graphite/show/host', [
            'host'  => $host->host_name,
            'view'  => 'compact'
        ])
    ?>"></div>
<?php endforeach ?>
<?php if ($hosts->hasMore()): ?>
    <div class="action-links">
        <?= $this->qlink(
            mt('monitoring', 'Show More'),
            $this->url()->without(array('view', 'limit')),
            null,
            [
                'class'             => 'action-link',
                'data-base-target'  => '_next'
            ]
        ) ?>
    </div>
<?php endif ?>
</div>
