<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->hostname ?></h1>
</div>
<div class="content">
<?php foreach ($this->images as $type => $imgs): ?>
<?php if (count($imgs) > 0): ?>

<div class="images"><h3><?= $this->escape(ucfirst($type)) ?></h3>
<?php foreach ($imgs as $img): ?>
<img class="svg" src="<?= $img->getUrl() ?>" alt="<?= $img->getTitle() ?>" title="<?= $img->getTitle() ?>" />
<?php endforeach ?>
</div>

<?php endif ?>
<?php endforeach ?>
</div>
