<ul class="legend">
<?php foreach ($this->template->getDatasources() as $ds): ?>
<?php if ($ds->isEnabled()): ?>
  <li><div class="color" style="background-color: <?= $this->escape($ds->getColorCss()) ?>"></div> <?= $this->qlink(
    $ds->getName(),
    $this->url()->with('disableDatasource', $ds->getPath()),
    null,
    array('title' => $this->translate('Click to disable'))
) ?></span></li>
<?php else: ?>
  <li class="disabled"><div class="color"></div> <?= $this->qlink(
    $ds->getName(),
    $this->url()->with('enableDatasource', $ds->getPath()),
    null,
    array('title' => $this->translate('Click to enable'))
) ?></span></li>
<?php endif ?>
<?php endforeach ?>
</ul>

