<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->translate('Graphite') ?></h1>
<form action="<?= $this->url()->without('disabled') ?>" method="get">
<?= $this->translate('Template') ?> <?= $this->formSelect('template', $this->templateName, array('class' => 'autosubmit'), $this->templates) ?>
 <?= $this->translate('Filter') ?> <?= $this->formSelect('filterColumn', $this->filterColumn, array('class' => 'autosubmit'), $this->filterColumns) ?>
<?php if ($this->filterColumn): ?>
 = <?= $this->formSelect('filterValue', $this->filterValue, array('class' => 'autosubmit'), $this->filterValues) ?>
<?php endif ?>
<?= $this->formSelect('start', $this->start, array('class' => 'autosubmit'), array(
    '-15min' => '15 minutes',
    '-60min' => '1 hour',
    '-2hour' => '4 hours',
    '-1day' => '1 day',
)) ?>
</form>
</div>

<div class="content">
<?php if (is_array($this->images)): ?>
<?= $this->render('show/legend.phtml') ?>
<?php foreach ($this->images as $title => $url): ?>
<img src="<?= $url ?>" class="graphiteImg" alt="" width="<?= $this->width ?>" height="<?= $this->height ?>" />
<?php endforeach ?>
<?php else: ?>
<?= $this->translate('Please make your selection') ?>
<?php endif ?>
</div>

