<?php
/** @var \Icinga\Web\View $this */

if (! $compact): ?>
<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->hostname ?>: <?= $this->service ?></h1>
</div>
<?php endif ?>

<div class="content">
<?php foreach ($this->images as $type => $imgs): ?>
<?php if (count($imgs) > 0): ?>

<div class="images">
<?php
if (! $compact) {
    echo "<h3>{$this->escape(ucfirst($type))}</h3>";
    echo $this->partial(
        'show/legend.phtml',
        array(
            'template'            => $this->templates[$type],
            'disabledDatasources' => $this->disabledDatasources
        )
    );
}
?>
<?php foreach ($imgs as $title => $url): ?>
<img src="<?= $url ?>" class="graphiteImg" alt="" width="<?= $this->width ?>" height="<?= $this->height ?>" />
<?php endforeach ?>
</div>

<?php endif ?>
<?php endforeach ?>

<?php if (! isset($title)): ?>
<p><?= $this->translate('No graphs found') ?></p>
<?php endif ?>

</div>
